### ISSUE TITLE
Incomplete vpx_img_fmt enum

### ISSUE THREAD

**Issue by jbis9051** [astraw/env-libvpx-sys#5]
libvpx provides 24 formats, however this library seems to provide 10

https://docs.rs/env-libvpx-sys/5.1.1/vpx_sys/enum.vpx_img_fmt.html

https://chromium.googlesource.com/webm/libvpx/+/frame_parallel/vpx/vpx_image.h#40

**Comment by jbis9051** [comment]
Disregard, apparently that's an older version from 2014. Google's Git web interface is a little confusing.
This is the current one which matches this library:  https://chromium.googlesource.com/webm/libvpx/+/refs/heads/main/vpx/vpx_image.h#38

**Comment by astraw** [comment]
Thanks for this. Yes, it looks like some formats were removed. The bindings are auto-generated and I can see the older versions indeed have more formats available than the more recent. If you build with the `VPX_VERSION` set to an older version you should pick up these definitions.
