### ISSUE TITLE
VPX_CODEC_ABI_MISMATCH on macOS

### ISSUE THREAD

**Issue by jbis9051** [astraw/env-libvpx-sys#6]
environment variables: `VPX_STATIC=1;VPX_VERSION=1.12.0`

I am getting VPX_CODEC_ABI_MISMATCH at runtime

**Comment by jbis9051** [comment]
```cpp
#define vpx_codec_enc_init(ctx, iface, cfg, flags) \
  vpx_codec_enc_init_ver(ctx, iface, cfg, flags, VPX_ENCODER_ABI_VERSION)

```

https://github.com/webmproject/libvpx/blob/705bf9de8c96cfe5301451f1d7e5c90a41c64e5f/vpx/vpx_encoder.h#L741-L743=

**Comment by astraw** [comment]
I don't follow your bug report but I updated the generated file for libvpx-1.12.0 and pushed release 5.1.2.
